name = "t4-api"
compatibility_date = "2023-01-01"
send_metrics = false
account_id = "your-account-id"

[[ d1_databases ]]
binding = "DB"
database_name = "production"
database_id = "your-database-id"
migrations_dir = "migrations"

# The necessary secrets are:
# - APP_URL - for preventing CORS errors
# - JWT_VERIFICATION_KEY - for Clerk @link https://clerk.dev
#
# For local development, you can create a file called .dev.vars and use dotenv syntax.
#
# For deployed environments, you can use wrangler secrets to set these values.
# For example:
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
# Or use the Cloudflare web interface.
# @link https://developers.cloudflare.com/workers/platform/environment-variables/#environment-variables-via-the-dashboard
# 
